# Generated by Django 4.2.5 on 2023-10-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwtapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=80)),
                ('book_title', models.CharField(max_length=80)),
                ('book_lesson', models.CharField(max_length=80)),
                ('book_price', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'Book',
            },
        ),
    ]
